CREATE OR REPLACE FUNCTION select_hotel(
	_id integer
        ) 
        RETURNS TABLE(type_room_amount bigint,name character varying(60), price numeric(10,2), country character varying(30), city character varying(30), address  character varying(60), stars integer, description_of_the_hotel text,climate_control boolean, high_speed_wifi boolean, p_bathroom boolean, tv_add_opt boolean, mini_bar boolean, in_room_safe boolean, work_features boolean, room_service boolean, room_cleaning boolean, transport_service boolean, luggage_storage boolean, full_time_supp boolean, fitness_center boolean, in_room_workout_equip boolean, spa boolean, swimming_pool_cov boolean, swimming_pool_unc boolean, business_center boolean, meeting_rooms boolean, breakfast_opt boolean, in_room_dining boolean, double_bed integer, single_bed integer, child_service boolean, price_child_service numeric(10,2), pet_service boolean, price_pet_service numeric(10,2), free_cancel boolean, group_of integer, description_of_type text ,photos_path text) AS $$
    BEGIN
         RETURN QUERY
        	SELECT COUNT(*) AS at_of_the_rm,hotels.name, room.price,hotels.country, hotels.city, hotels.address, hotels.stars, hotels.description, service_of_rooms.climate_control, service_of_rooms.high_speed_wifi, service_of_rooms.p_bathroom, service_of_rooms.tv_add_opt, service_of_rooms.mini_bar, service_of_rooms.in_room_safe, service_of_rooms.work_features, service_of_rooms.room_service, service_of_rooms.room_cleaning, service_of_rooms.transport_service, service_of_rooms.luggage_storage, service_of_rooms.full_time_supp, service_of_rooms.fitness_center, service_of_rooms.in_room_workout_equip, service_of_rooms.spa, service_of_rooms.swimming_pool_cov, service_of_rooms.swimming_pool_unc, service_of_rooms.business_center, service_of_rooms.meeting_rooms, service_of_rooms.breakfast_opt, service_of_rooms.in_room_dining, service_of_rooms.double_bed, service_of_rooms.single_bed, service_of_rooms.child_service, service_of_rooms.pr_ch_sv, service_of_rooms.pet_service, service_of_rooms.pr_pet_sv, service_of_rooms.free_cancel, service_of_rooms.group_of,room.description, h_photos_path
            FROM hotels
            JOIN room ON room.fk_hotel_id = hotels.id
            JOIN hotels_photos ON hotels_photos.id = hotels.id 
            JOIN room_type ON room_type.id = room.fk_room_type_id 
            JOIN service_of_rooms ON service_of_rooms.fk_hotel_id = hotels.id AND service_of_rooms.fk_room_type_id = room_type.id
            WHERE is_reserved = false AND service_of_rooms.fk_hotel_id = _id
            GROUP BY room_type.id,hotels.id, hotels.name, room.price,hotels.country, hotels.city, hotels.address, hotels.stars, hotels.description, service_of_rooms.climate_control, service_of_rooms.high_speed_wifi, service_of_rooms.p_bathroom, service_of_rooms.tv_add_opt, service_of_rooms.mini_bar, service_of_rooms.in_room_safe, service_of_rooms.work_features, service_of_rooms.room_service, service_of_rooms.room_cleaning, service_of_rooms.transport_service, service_of_rooms.luggage_storage, service_of_rooms.full_time_supp, service_of_rooms.fitness_center, service_of_rooms.in_room_workout_equip, service_of_rooms.spa, service_of_rooms.swimming_pool_cov, service_of_rooms.swimming_pool_unc, service_of_rooms.business_center, service_of_rooms.meeting_rooms, service_of_rooms.breakfast_opt, service_of_rooms.in_room_dining, service_of_rooms.double_bed, service_of_rooms.single_bed, service_of_rooms.child_service, service_of_rooms.pr_ch_sv, service_of_rooms.pet_service, service_of_rooms.pr_pet_sv, service_of_rooms.free_cancel, service_of_rooms.group_of, room_type.description, room.fk_room_type_id, room.description, h_photos_path;
    END;
$$ LANGUAGE plpgsql;